
server:
  port: 8090
spring:
  application:
    name: "loans"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: 'root'
  sql:
    init:
      mode: always
  config: 
    activate:
     on-profile: "qa"
     
build: 
  version: '2.0'

loans: 
  message: "Welcome to Bank Loans related QA APIs"
  contactDetails:
    name: "Suresh Pokhrail - QA Leads"
    email: "pokhrailsuresh5@gmail.com"
  contact: 
      -7500065026
      -7500065027