server:
  port: 8090
spring:
  application:
    name: "loans"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: 'root'
  jpa:
     #database-platform: org.hibernate.dialect.H2Dialect
    #hibernate:
     # ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always 
  config:
    import : "configserver:http://configserver:8071/"
  rabbitmq :
    host : "localhost"
    port : 5672
    username : "guest"
    password : "guest"

management : 
  endpoints :
    web :
      exposure :
        include : "*"

 