
server:
  port: 9000
spring:
  application:
    name: "cards"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3308/cardsdb
    username: root
    password: 'root'
  sql:
    init:
      mode: always
  config: 
    activate:
     on-profile: "qa"
     
build: 
  version: '2.0'

cards: 
  message: "Welcome to Bank Cards related QA APIs"
  contactDetails:
    name: "Suresh Pokhrail - QA Leads"
    email: "pokhrailsuresh5@gmail.com"
  contact: 
      -7505065026
      -7555065027